name: 카이아 지갑 추적기

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  track-wallet:
    runs-on: ubuntu-latest
    
    steps:
    - name: 체크아웃
      uses: actions/checkout@v4
    
    - name: Node.js 설치
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        # 캐시 설정 완전 제거
    
    - name: 의존성 직접 설치
      run: |
        rm -f package-lock.json
        npm install node-fetch@2.6.7 --no-package-lock
    
    - name: 카이아 지갑 추적 실행
      run: node wallet-tracker.js
      env:
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        KAIA_WALLET_ADDRESS: ${{ secrets.KAIA_WALLET_ADDRESS }}
